import { promises as fs } from "fs"
import path from "path"
import { NextRequest, NextResponse } from "next/server"

const AUTO_LEADS_FILE = path.join(process.cwd(), "..", "courtlab-crm", "leads-research", "auto-generated-leads.json")

interface AutoGeneratedLead {
  id: string
  name: string
  type: string
  location: string
  painPoint: string
  approach: string
  confidence: number
  source: string
  tags: string[]
}

export async function GET() {
  try {
    const data = await fs.readFile(AUTO_LEADS_FILE, "utf-8")
    const leads = JSON.parse(data) as AutoGeneratedLead[]
    return NextResponse.json({ leads, count: leads.length })
  } catch (error) {
    return NextResponse.json({ leads: [], count: 0 })
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { leads } = body

    if (!Array.isArray(leads)) {
      return NextResponse.json({ error: "Leads must be an array" }, { status: 400 })
    }

    // Create directory if it doesn't exist
    const dir = path.dirname(AUTO_LEADS_FILE)
    await fs.mkdir(dir, { recursive: true })

    // Save leads
    await fs.writeFile(AUTO_LEADS_FILE, JSON.stringify(leads, null, 2))

    return NextResponse.json({
      success: true,
      count: leads.length,
      message: `Saved ${leads.length} auto-generated leads`,
    })
  } catch (error) {
    return NextResponse.json({ error: "Failed to save leads" }, { status: 500 })
  }
}
